In [3]:
s = 'dhjdhdggdhhg'

In [4]:
s[0:3]
s[:5]

'dhjdh'

In [5]:
# List
my_list = ['a', 'b','c']

In [6]:
my_list.append('d')

In [7]:
my_list

['a', 'b', 'c', 'd']

In [8]:
my_list[1:3]

['b', 'c']

In [9]:
my_list[0] = 'NEW'

In [10]:
my_list

['NEW', 'b', 'c', 'd']

In [11]:
happy = [1,2,[3,4]]

In [12]:
happy

[1, 2, [3, 4]]

In [13]:
happy[2][1]

4

In [14]:
# Dictionary
d = {'sam':'hi','helly':'bye'}

In [15]:
print(d['sam'])

hi


In [16]:
d = {'k1':{'innerkey':[1,2,3]}}

In [17]:
d['k1']['innerkey'][2]

3

In [18]:
if 1 == 2:
    print('First')
else:
    print('Last')

Last


In [19]:
if 1 == 2:
    print('First')
elif 3 == 3:
    print('Second')
else:
    print('Last')

Second


In [20]:
seq = [1,2,3,4,5]

In [21]:
for num in seq:
    print(num + 1)

2
3
4
5
6


In [22]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [23]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [24]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
x = [1,2,3,4]

In [26]:
out = []
for i in x:
    out.append(i**2)

In [27]:
print(out)

[1, 4, 9, 16]


In [28]:
# List comprehension
out = [i**2 for i in x]

In [29]:
print(out)

[1, 4, 9, 16]


In [30]:
def my_func(name):
    print('Hello ' +name)
    

In [31]:
my_func('John')

Hello John


In [32]:
def square(num):
    return num**2

In [33]:
output = square(2)

In [34]:
output

4

In [35]:
seq = [1,2,3,4,5]

In [36]:
list(map(square, seq))

[1, 4, 9, 16, 25]

In [37]:
t = lambda var : var*2

In [38]:
t(6)

12

In [39]:
list(map(lambda num : num*3, seq))

[3, 6, 9, 12, 15]

In [40]:
list(filter(lambda num: num%2 == 0,seq))

[2, 4]

In [41]:
x = [(1,2),(3,4),(5,6)]

In [42]:
for (a,b) in x:
    print(b)

2
4
6


In [43]:
# Question
planet = "Earth"
diameter = "12742"

In [44]:
print('The diameter of {} is {} kilometer'.format(planet,diameter))

The diameter of Earth is 12742 kilometer


In [45]:
def domainget(email):
    return email.split('@')[1]

In [46]:
domainget('user@domain.com')

'domain.com'

In [47]:
# create a basic function that return true if the word "dog" is contained in the input string
def findDog(s):
    return 'dog' in s.lower().split()

In [48]:
findDog('Dog is barking')

True

In [49]:
'Dog' in 'Dog is barking'

True

In [50]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [51]:
countDog('This dog run faster than other dog dude!')

2

In [52]:
seq = ['soup', 'dog', 'salad', 'horse', 'butterfly']

In [53]:
list(filter(lambda word: word[0] == 's',seq))

['soup', 'salad']

<!-- Numpy Arrays -->

In [54]:
# NUMPY
my_list = [[1,2,3],[4,5,6],[7,8,0]]

In [55]:
import numpy as np
np.array(my_list)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [56]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.random.randint(1,100,20)

array([ 2, 30, 14, 37, 89, 11, 75,  7, 17, 14, 57, 75, 55, 18, 99, 58, 36,
       59, 64, 37])

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[1:5]

array([1, 2, 3, 4])

In [62]:
arr[0:5] = 100

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
slice_of_arr = arr[0:6]

In [65]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [66]:
slice_of_arr[:] = 56

In [67]:
slice_of_arr 

array([56, 56, 56, 56, 56, 56])

In [68]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
arr_2d[1,0]

20

In [71]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [72]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
# Pandas Series

In [79]:
import numpy as np
import pandas as pd

In [80]:
labels = {'a','b','c'}
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}   #dictionary

In [81]:
pd.Series(data = my_data, index = labels)

b    10
a    20
c    30
dtype: int64

In [82]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [83]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','UK','Africa'])

In [84]:
ser1

USA       1
Japan     2
UK        3
Africa    4
dtype: int64

In [85]:
from numpy.random import randn

In [86]:
np.random.seed(101)

In [87]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [88]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [89]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [90]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [91]:
df['new'] = df['W'] + df['X']

In [92]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [93]:
df.drop('new', axis = 1,inplace = True)

In [94]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [95]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [96]:
df.shape

(5, 4)

In [97]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [98]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [99]:
df.loc['B','Y']

-0.8480769834036315

In [100]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [101]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [102]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [103]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [104]:
df[df['W'] >0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
resultdf = df[df['Z'] >0]

In [106]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [107]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [108]:
df[df['W'] >0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [109]:
df[df['W'] >0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [110]:
True and True

True

In [111]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [112]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [113]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [114]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [115]:
newind = "CA NY CA US UK".split()

In [116]:
df['States'] = newind

In [117]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     CA
D  0.188695 -0.758872 -0.933237  0.955057     US
E  0.190794  1.978757  2.605967  0.683509     UK

In [118]:
df.set_index("States")

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
CA     -2.018168  0.740122  0.528813 -0.589001
US      0.188695 -0.758872 -0.933237  0.955057
UK      0.190794  1.978757  2.605967  0.683509

In [120]:
# Dataframe part 3


outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2',]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index )

In [121]:
hier_index 

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [123]:
df = pd.DataFrame(randn(6,2), hier_index, ['A','B'])

In [124]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [125]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [126]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [129]:
df.index.names = ['Groups','Num']

In [130]:
df

A         B
Groups Num                    
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [133]:
df.loc['G2'].loc[2].loc['B']

0.07295967531703869

In [135]:
# xs = cross section

df.xs(1,level = 'Num')

A         B
Groups                    
G1      0.302665  1.693723
G2      0.166905  0.184502

In [ ]:
# Missing Data

