In [1]:
s = 'dhjdhdggdhhg'

In [2]:
s[0:3]
s[:5]

'dhjdh'

In [3]:
# List
my_list = ['a', 'b','c']

In [4]:
my_list.append('d')

In [5]:
my_list

['a', 'b', 'c', 'd']

In [6]:
my_list[1:3]

['b', 'c']

In [7]:
my_list[0] = 'NEW'

In [8]:
my_list

['NEW', 'b', 'c', 'd']

In [9]:
happy = [1,2,[3,4]]

In [10]:
happy

[1, 2, [3, 4]]

In [11]:
happy[2][1]

4

In [12]:
# Dictionary
d = {'sam':'hi','helly':'bye'}

In [13]:
print(d['sam'])

hi


In [14]:
d = {'k1':{'innerkey':[1,2,3]}}

In [15]:
d['k1']['innerkey'][2]

3

In [16]:
if 1 == 2:
    print('First')
else:
    print('Last')

Last


In [17]:
if 1 == 2:
    print('First')
elif 3 == 3:
    print('Second')
else:
    print('Last')

Second


In [18]:
seq = [1,2,3,4,5]

In [19]:
for num in seq:
    print(num + 1)

2
3
4
5
6


In [20]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [21]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [22]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
x = [1,2,3,4]

In [24]:
out = []
for i in x:
    out.append(i**2)

In [25]:
print(out)

[1, 4, 9, 16]


In [26]:
# List comprehension
out = [i**2 for i in x]

In [27]:
print(out)

[1, 4, 9, 16]


In [28]:
def my_func(name):
    print('Hello ' +name)
    

In [29]:
my_func('John')

Hello John


In [30]:
def square(num):
    return num**2

In [31]:
output = square(2)

In [32]:
output

4

In [33]:
seq = [1,2,3,4,5]

In [34]:
list(map(square, seq))

[1, 4, 9, 16, 25]

In [35]:
t = lambda var : var*2

In [36]:
t(6)

12

In [37]:
list(map(lambda num : num*3, seq))

[3, 6, 9, 12, 15]

In [38]:
list(filter(lambda num: num%2 == 0,seq))

[2, 4]

In [39]:
x = [(1,2),(3,4),(5,6)]

In [40]:
for (a,b) in x:
    print(b)

2
4
6


In [41]:
# Question
planet = "Earth"
diameter = "12742"

In [42]:
print('The diameter of {} is {} kilometer'.format(planet,diameter))

The diameter of Earth is 12742 kilometer


In [43]:
def domainget(email):
    return email.split('@')[1]

In [44]:
domainget('user@domain.com')

'domain.com'

In [45]:
# create a basic function that return true if the word "dog" is contained in the input string
def findDog(s):
    return 'dog' in s.lower().split()

In [46]:
findDog('Dog is barking')

True

In [47]:
'Dog' in 'Dog is barking'

True

In [48]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [49]:
countDog('This dog run faster than other dog dude!')

2

In [50]:
seq = ['soup', 'dog', 'salad', 'horse', 'butterfly']

In [51]:
list(filter(lambda word: word[0] == 's',seq))

['soup', 'salad']

<!-- Numpy Arrays -->

In [52]:
# NUMPY
my_list = [[1,2,3],[4,5,6],[7,8,0]]

In [53]:
import numpy as np
np.array(my_list)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [54]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.random.randint(1,100,20)

array([23,  3, 35, 32, 21, 80, 50, 99, 65, 43, 73, 81, 19, 17, 49, 59, 72,
       96, 28, 51])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5] = 100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [64]:
slice_of_arr[:] = 56

In [65]:
slice_of_arr 

array([56, 56, 56, 56, 56, 56])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[1,0]

20

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# Pandas Series

In [77]:
import numpy as np
import pandas as pd

In [78]:
labels = {'a','b','c'}
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}   #dictionary

In [79]:
pd.Series(data = my_data, index = labels)

a    10
c    20
b    30
dtype: int64

In [80]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [81]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','UK','Africa'])

In [82]:
ser1

USA       1
Japan     2
UK        3
Africa    4
dtype: int64

In [83]:
from numpy.random import randn

In [84]:
np.random.seed(101)

In [85]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [86]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [87]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [88]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [89]:
df['new'] = df['W'] + df['X']

In [90]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [91]:
df.drop('new', axis = 1,inplace = True)

In [92]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [93]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [94]:
df.shape

(5, 4)

In [95]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [97]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [98]:
df.loc['B','Y']

-0.8480769834036315

In [99]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077