In [1]:
s = 'dhjdhdggdhhg'

In [2]:
s[0:3]
s[:5]

'dhjdh'

In [3]:
# List
my_list = ['a', 'b','c']

In [4]:
my_list.append('d')

In [5]:
my_list

['a', 'b', 'c', 'd']

In [6]:
my_list[1:3]

['b', 'c']

In [7]:
my_list[0] = 'NEW'

In [8]:
my_list

['NEW', 'b', 'c', 'd']

In [9]:
happy = [1,2,[3,4]]

In [10]:
happy

[1, 2, [3, 4]]

In [11]:
happy[2][1]

4

In [12]:
# Dictionary
d = {'sam':'hi','helly':'bye'}

In [13]:
print(d['sam'])

hi


In [14]:
d = {'k1':{'innerkey':[1,2,3]}}

In [15]:
d['k1']['innerkey'][2]

3

In [16]:
if 1 == 2:
    print('First')
else:
    print('Last')

Last


In [17]:
if 1 == 2:
    print('First')
elif 3 == 3:
    print('Second')
else:
    print('Last')

Second


In [18]:
seq = [1,2,3,4,5]

In [19]:
for num in seq:
    print(num + 1)

2
3
4
5
6


In [20]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [21]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [22]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
x = [1,2,3,4]

In [24]:
out = []
for i in x:
    out.append(i**2)

In [25]:
print(out)

[1, 4, 9, 16]


In [26]:
# List comprehension
out = [i**2 for i in x]

In [27]:
print(out)

[1, 4, 9, 16]


In [28]:
def my_func(name):
    print('Hello ' +name)
    

In [29]:
my_func('John')

Hello John


In [30]:
def square(num):
    return num**2

In [31]:
output = square(2)

In [32]:
output

4

In [33]:
seq = [1,2,3,4,5]

In [34]:
list(map(square, seq))

[1, 4, 9, 16, 25]

In [35]:
t = lambda var : var*2

In [36]:
t(6)

12

In [37]:
list(map(lambda num : num*3, seq))

[3, 6, 9, 12, 15]

In [38]:
list(filter(lambda num: num%2 == 0,seq))

[2, 4]

In [39]:
x = [(1,2),(3,4),(5,6)]

In [40]:
for (a,b) in x:
    print(b)

2
4
6


In [41]:
# Question
planet = "Earth"
diameter = "12742"

In [42]:
print('The diameter of {} is {} kilometer'.format(planet,diameter))

The diameter of Earth is 12742 kilometer


In [43]:
def domainget(email):
    return email.split('@')[1]

In [44]:
domainget('user@domain.com')

'domain.com'

In [45]:
# create a basic function that return true if the word "dog" is contained in the input string
def findDog(s):
    return 'dog' in s.lower().split()

In [46]:
findDog('Dog is barking')

True

In [47]:
'Dog' in 'Dog is barking'

True

In [48]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [49]:
countDog('This dog run faster than other dog dude!')

2

In [50]:
seq = ['soup', 'dog', 'salad', 'horse', 'butterfly']

In [51]:
list(filter(lambda word: word[0] == 's',seq))

['soup', 'salad']

<!-- Numpy Arrays -->

In [52]:
# NUMPY
my_list = [[1,2,3],[4,5,6],[7,8,0]]

In [53]:
import numpy as np
np.array(my_list)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [54]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.random.randint(1,100,20)

array([18, 82, 81, 87, 92, 23, 53, 22, 30, 66, 67, 42, 46, 97, 73, 42, 33,
       28, 55, 47])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5] = 100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [64]:
slice_of_arr[:] = 56

In [65]:
slice_of_arr 

array([56, 56, 56, 56, 56, 56])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[1,0]

20

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# Pandas Series

In [77]:
import numpy as np
import pandas as pd

In [78]:
labels = {'a','b','c'}
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}   #dictionary

In [79]:
pd.Series(data = my_data, index = labels)

b    10
c    20
a    30
dtype: int64

In [80]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [81]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','UK','Africa'])

In [82]:
ser1

USA       1
Japan     2
UK        3
Africa    4
dtype: int64

In [83]:
from numpy.random import randn

In [84]:
np.random.seed(101)

In [85]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [86]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [87]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [88]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [89]:
df['new'] = df['W'] + df['X']

In [90]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [91]:
df.drop('new', axis = 1,inplace = True)

In [92]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [93]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [94]:
df.shape

(5, 4)

In [95]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [96]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [97]:
df.loc['B','Y']

-0.8480769834036315

In [98]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [99]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [100]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [101]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [102]:
df[df['W'] >0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [103]:
resultdf = df[df['Z'] >0]

In [104]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [106]:
df[df['W'] >0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [107]:
df[df['W'] >0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [108]:
True and True

True

In [109]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [111]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [112]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [113]:
newind = "CA NY CA US UK".split()

In [114]:
df['States'] = newind

In [115]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     CA
D  0.188695 -0.758872 -0.933237  0.955057     US
E  0.190794  1.978757  2.605967  0.683509     UK

In [116]:
df.set_index("States")

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
CA     -2.018168  0.740122  0.528813 -0.589001
US      0.188695 -0.758872 -0.933237  0.955057
UK      0.190794  1.978757  2.605967  0.683509

In [117]:
# Dataframe part 3


outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2',]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index )

In [118]:
hier_index 

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [119]:
df = pd.DataFrame(randn(6,2), hier_index, ['A','B'])

In [120]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [121]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [122]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [123]:
df.index.names = ['Groups','Num']

In [124]:
df

A         B
Groups Num                    
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [125]:
df.loc['G2'].loc[2].loc['B']

0.07295967531703869

In [126]:
# xs = cross section

df.xs(1,level = 'Num')

A         B
Groups                    
G1      0.302665  1.693723
G2      0.166905  0.184502

In [131]:
# Missing Data

d = {'A':[1,2,np.nan], 'B':[5,np.nan,7], 'C':[1,2,3]}

In [132]:
newdf = pd.DataFrame(d)

In [133]:
newdf

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  7.0  3

In [135]:
newdf.dropna()

A    B  C
0  1.0  5.0  1

In [136]:
newdf.dropna(axis = 1)

C
0  1
1  2
2  3

In [138]:
newdf.fillna(value = 'FILL NA')

A        B  C
0        1        5  1
1        2  FILL NA  2
2  FILL NA        7  3

In [141]:
newdf['A'].fillna(value = newdf['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [152]:
# Groupby in pandas


data = { 'company':['Google','Google','Paypal','Paypal','Amazon','Amazon'],
         'Person': ['Tamal','Charlie','Sam','Venessa','Mahi','Smith'],
         'Sales' : [200,100,520,890,560,680]
        }

In [153]:
df1 = pd.DataFrame(data)

In [154]:
df1

company   Person  Sales
0  Google    Tamal    200
1  Google  Charlie    100
2  Paypal      Sam    520
3  Paypal  Venessa    890
4  Amazon     Mahi    560
5  Amazon    Smith    680

In [155]:
grcomp = df1.groupby('company')

In [156]:
grcomp.mean()

Sales
company       
Amazon     620
Google     150
Paypal     705

In [157]:
grcomp.mean().loc['Amazon']

Sales    620
Name: Amazon, dtype: int64

In [158]:
df1.groupby('company').sum().loc['Paypal']

Sales    1410
Name: Paypal, dtype: int64

In [159]:
df1.groupby('company').count()

Person  Sales
company               
Amazon        2      2
Google        2      2
Paypal        2      2

In [160]:
df1.groupby('company').min()

Person  Sales
company                
Amazon      Mahi    560
Google   Charlie    100
Paypal       Sam    520

In [161]:
df1.groupby('company').describe()

Sales                                                      
        count   mean         std    min    25%    50%    75%    max
company                                                            
Amazon    2.0  620.0   84.852814  560.0  590.0  620.0  650.0  680.0
Google    2.0  150.0   70.710678  100.0  125.0  150.0  175.0  200.0
Paypal    2.0  705.0  261.629509  520.0  612.5  705.0  797.5  890.0

In [163]:
df1.groupby('company').describe().transpose()['Amazon']

Sales  count      2.000000
       mean     620.000000
       std       84.852814
       min      560.000000
       25%      590.000000
       50%      620.000000
       75%      650.000000
       max      680.000000
Name: Amazon, dtype: float64

In [164]:
# Merging,Joining,Concatenating data frame

In [165]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [166]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [167]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [168]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [169]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [170]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [173]:
pd.concat([df1,df2,df3])    #according to row

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [174]:
pd.concat([df1,df2,df3],axis = 1) #according to column

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [177]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [179]:
pd.merge(left,right,how = 'inner', on = 'key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [184]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})

In [185]:
pd.merge(left,right, on = ['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [188]:
dfnew1 = pd.DataFrame({'col1': [1,2,3,4],
                      'col2': [444,555,666,444],
                      'col3': ['abc','def','ghi','xyz']})
dfnew1.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [189]:
dfnew1['col2'].unique()

KeyError: 'col2'