In [1]:
s = 'dhjdhdggdhhg'

In [2]:
s[0:3]
s[:5]

'dhjdh'

In [3]:
# List
my_list = ['a', 'b','c']

In [4]:
my_list.append('d')

In [5]:
my_list

['a', 'b', 'c', 'd']

In [6]:
my_list[1:3]

['b', 'c']

In [7]:
my_list[0] = 'NEW'

In [8]:
my_list

['NEW', 'b', 'c', 'd']

In [9]:
happy = [1,2,[3,4]]

In [10]:
happy

[1, 2, [3, 4]]

In [11]:
happy[2][1]

4

In [12]:
# Dictionary
d = {'sam':'hi','helly':'bye'}

In [13]:
print(d['sam'])

hi


In [14]:
d = {'k1':{'innerkey':[1,2,3]}}

In [15]:
d['k1']['innerkey'][2]

3

In [16]:
if 1 == 2:
    print('First')
else:
    print('Last')

Last


In [17]:
if 1 == 2:
    print('First')
elif 3 == 3:
    print('Second')
else:
    print('Last')

Second


In [18]:
seq = [1,2,3,4,5]

In [19]:
for num in seq:
    print(num + 1)

2
3
4
5
6


In [20]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [21]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [22]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
x = [1,2,3,4]

In [24]:
out = []
for i in x:
    out.append(i**2)

In [25]:
print(out)

[1, 4, 9, 16]


In [26]:
# List comprehension
out = [i**2 for i in x]

In [27]:
print(out)

[1, 4, 9, 16]


In [28]:
def my_func(name):
    print('Hello ' +name)
    

In [29]:
my_func('John')

Hello John


In [30]:
def square(num):
    return num**2

In [31]:
output = square(2)

In [32]:
output

4

In [33]:
seq = [1,2,3,4,5]

In [34]:
list(map(square, seq))

[1, 4, 9, 16, 25]

In [35]:
t = lambda var : var*2

In [36]:
t(6)

12

In [37]:
list(map(lambda num : num*3, seq))

[3, 6, 9, 12, 15]

In [38]:
list(filter(lambda num: num%2 == 0,seq))

[2, 4]

In [39]:
x = [(1,2),(3,4),(5,6)]

In [40]:
for (a,b) in x:
    print(b)

2
4
6


In [41]:
# Question
planet = "Earth"
diameter = "12742"

In [42]:
print('The diameter of {} is {} kilometer'.format(planet,diameter))

The diameter of Earth is 12742 kilometer


In [43]:
def domainget(email):
    return email.split('@')[1]

In [44]:
domainget('user@domain.com')

'domain.com'

In [45]:
# create a basic function that return true if the word "dog" is contained in the input string
def findDog(s):
    return 'dog' in s.lower().split()

In [46]:
findDog('Dog is barking')

True

In [47]:
'Dog' in 'Dog is barking'

True

In [48]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [49]:
countDog('This dog run faster than other dog dude!')

2

In [50]:
seq = ['soup', 'dog', 'salad', 'horse', 'butterfly']

In [51]:
list(filter(lambda word: word[0] == 's',seq))

['soup', 'salad']

<!-- Numpy Arrays -->

In [52]:
# NUMPY
my_list = [[1,2,3],[4,5,6],[7,8,0]]

In [53]:
import numpy as np
np.array(my_list)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [54]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.random.randint(1,100,20)

array([53, 21, 28, 76, 53, 47, 45, 36, 17, 31,  7, 99, 43, 38, 57, 99, 85,
       14, 86,  8])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
arr[0:5] = 100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr 

array([100, 100, 100, 100, 100,   5])

In [64]:
slice_of_arr[:] = 56

In [65]:
slice_of_arr 

array([56, 56, 56, 56, 56, 56])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[1,0]

20

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# Pandas Series

In [77]:
import numpy as np
import pandas as pd

In [78]:
labels = {'a','b','c'}
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}   #dictionary

In [79]:
pd.Series(data = my_data, index = labels)

c    10
b    20
a    30
dtype: int64

In [80]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [81]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','UK','Africa'])

In [82]:
ser1

USA       1
Japan     2
UK        3
Africa    4
dtype: int64

In [83]:
from numpy.random import randn

In [84]:
np.random.seed(101)

In [85]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [86]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [87]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [88]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [89]:
df['new'] = df['W'] + df['X']

In [90]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [91]:
df.drop('new', axis = 1,inplace = True)

In [92]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [93]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [94]:
df.shape

(5, 4)

In [95]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [96]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [97]:
df.loc['B','Y']

-0.8480769834036315

In [98]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [99]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [100]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [101]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [102]:
df[df['W'] >0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [103]:
resultdf = df[df['Z'] >0]

In [104]:
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [105]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [106]:
df[df['W'] >0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [107]:
df[df['W'] >0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [108]:
True and True

True

In [109]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [111]:
df[(df['W']>0) | (df['Y']>1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [112]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [113]:
newind = "CA NY CA US UK".split()

In [114]:
df['States'] = newind

In [115]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     CA
D  0.188695 -0.758872 -0.933237  0.955057     US
E  0.190794  1.978757  2.605967  0.683509     UK

In [116]:
df.set_index("States")

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
CA     -2.018168  0.740122  0.528813 -0.589001
US      0.188695 -0.758872 -0.933237  0.955057
UK      0.190794  1.978757  2.605967  0.683509

In [117]:
# Dataframe part 3


outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2',]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index )

In [118]:
hier_index 

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [119]:
df = pd.DataFrame(randn(6,2), hier_index, ['A','B'])

In [120]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [121]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [122]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [123]:
df.index.names = ['Groups','Num']

In [124]:
df

A         B
Groups Num                    
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [125]:
df.loc['G2'].loc[2].loc['B']

0.07295967531703869

In [126]:
# xs = cross section

df.xs(1,level = 'Num')

A         B
Groups                    
G1      0.302665  1.693723
G2      0.166905  0.184502

In [127]:
# Missing Data

d = {'A':[1,2,np.nan], 'B':[5,np.nan,7], 'C':[1,2,3]}

In [128]:
newdf = pd.DataFrame(d)

In [129]:
newdf

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  7.0  3

In [130]:
newdf.dropna()

A    B  C
0  1.0  5.0  1

In [131]:
newdf.dropna(axis = 1)

C
0  1
1  2
2  3

In [132]:
newdf.fillna(value = 'FILL NA')

A        B  C
0        1        5  1
1        2  FILL NA  2
2  FILL NA        7  3

In [133]:
newdf['A'].fillna(value = newdf['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [134]:
# Groupby in pandas


data = { 'company':['Google','Google','Paypal','Paypal','Amazon','Amazon'],
         'Person': ['Tamal','Charlie','Sam','Venessa','Mahi','Smith'],
         'Sales' : [200,100,520,890,560,680]
        }

In [135]:
df1 = pd.DataFrame(data)

In [136]:
df1

company   Person  Sales
0  Google    Tamal    200
1  Google  Charlie    100
2  Paypal      Sam    520
3  Paypal  Venessa    890
4  Amazon     Mahi    560
5  Amazon    Smith    680

In [137]:
grcomp = df1.groupby('company')

In [138]:
grcomp.mean()

Sales
company       
Amazon     620
Google     150
Paypal     705

In [139]:
grcomp.mean().loc['Amazon']

Sales    620
Name: Amazon, dtype: int64

In [140]:
df1.groupby('company').sum().loc['Paypal']

Sales    1410
Name: Paypal, dtype: int64

In [141]:
df1.groupby('company').count()

Person  Sales
company               
Amazon        2      2
Google        2      2
Paypal        2      2

In [142]:
df1.groupby('company').min()

Person  Sales
company                
Amazon      Mahi    560
Google   Charlie    100
Paypal       Sam    520

In [143]:
df1.groupby('company').describe()

Sales                                                      
        count   mean         std    min    25%    50%    75%    max
company                                                            
Amazon    2.0  620.0   84.852814  560.0  590.0  620.0  650.0  680.0
Google    2.0  150.0   70.710678  100.0  125.0  150.0  175.0  200.0
Paypal    2.0  705.0  261.629509  520.0  612.5  705.0  797.5  890.0

In [144]:
df1.groupby('company').describe().transpose()['Amazon']

Sales  count      2.000000
       mean     620.000000
       std       84.852814
       min      560.000000
       25%      590.000000
       50%      620.000000
       75%      650.000000
       max      680.000000
Name: Amazon, dtype: float64

In [145]:
# Merging,Joining,Concatenating data frame

In [146]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [147]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [148]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [149]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [150]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [151]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [152]:
pd.concat([df1,df2,df3])    #according to row

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [153]:
pd.concat([df1,df2,df3],axis = 1) #according to column

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [154]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [155]:
pd.merge(left,right,how = 'inner', on = 'key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [156]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})

In [157]:
pd.merge(left,right, on = ['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [158]:
dfnew1 = pd.DataFrame({'col1': [1,2,3,4],
                      'col2': [444,555,666,444],
                      'col3': ['abc','def','ghi','xyz']})
dfnew1.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [159]:
dfnew1['col2'].unique()

array([444, 555, 666], dtype=int64)

In [160]:
dfnew1[dfnew1['col1']>2]

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [161]:
dfnew1['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [162]:
def times2(x):
    return x*2

In [163]:
dfnew1['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [164]:
dfnew1['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [165]:
dfnew1.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [166]:
dfnew1.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [167]:
# SF Salaries Exercise Overview

In [168]:
import pandas as pd

In [169]:
sal = pd.read_csv('Salaries.csv')

In [170]:
sal.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [171]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [172]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [173]:
sal['OvertimePay'].max()

245131.88

In [174]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']

Id     EmployeeName                   JobTitle    BasePay  OvertimePay  \
24  25  JOSEPH DRISCOLL  CAPTAIN, FIRE SUPPRESSION  140546.86     97868.77   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
24  31909.28       NaN  270324.91         270324.91  2011    NaN   

           Agency  Status  
24  San Francisco     NaN

In [175]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL'] ['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [176]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [177]:
sal['TotalPayBenefits'].min()

-618.13

In [178]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [179]:
sal.groupby('Year').mean()

Id       BasePay  OvertimePay     OtherPay      Benefits  \
Year                                                                   
2011   18080.0  63595.956517  4531.065429  3617.081926           NaN   
2012   54542.5  65436.406857  5023.417824  3653.437583  26439.966967   
2013   91728.5  69630.030216  5281.641980  3819.969007  23829.076572   
2014  129593.0  66564.421924  5401.993737  3505.421251  24789.601756   

          TotalPay  TotalPayBenefits  Notes  Status  
Year                                                 
2011  71744.103871      71744.103871    NaN     NaN  
2012  74113.262265     100553.229232    NaN     NaN  
2013  77611.443142     101440.519714    NaN     NaN  
2014  75463.918140     100250.918884    NaN     NaN

In [180]:
sal['JobTitle'].nunique()

2159

In [181]:
# top 5 most common jobs

sal['JobTitle'].value_counts().head()

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [182]:
sum(sal[sal['Year'] == 2013] ['JobTitle'].value_counts() == 1)

202

In [183]:
# how many people have the word Chief in their job title

In [184]:
def chief_string(title):
    if 'chief' in title.lower().split():
        return True
    else:
        return False

In [185]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

477

In [186]:
sal['JobTitle'].apply(lambda x: chief_string(x)).value_counts()

False    148177
True        477
Name: JobTitle, dtype: int64

In [187]:
# Ecommerce Purchases Exercise

In [188]:
import pandas as pd

In [189]:
ecom = pd.read_csv('Ecommerce Purchases')

In [190]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [191]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [192]:
ecom['Purchase Price'].mean()

50.34730200000025

In [193]:
ecom['Purchase Price'].max()

99.99

In [194]:
ecom['Purchase Price'].min()

0.0

In [197]:
ecom[ecom['Language'] == 'en'].head(3)

Address    Lot AM or PM  \
11            349 Laurie Parks\nThomasview, ID 08970  30 kK       PM   
12   733 Heather Rest Apt. 670\nBoltonport, UT 78662  69 DO       AM   
22  625 Laura Summit Suite 112\nShortmouth, AK 97156  45 oa       PM   

                                         Browser Info       Company  \
11  Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...    Kim-Oliver   
12  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 ...  Moore-Martin   
22  Mozilla/5.0 (Windows 95) AppleWebKit/5342 (KHT...   Burnett Ltd   

         Credit Card CC Exp Date  CC Security Code    CC Provider  \
11   869975209012056       06/26              9717   JCB 15 digit   
12  5115990487067905       05/26               119  VISA 16 digit   
22  3158663456056588       07/22               508       Discover   

                        Email                      Job      IP Address  \
11   johnnymiller@coleman.com  Diagnostic radiographer  128.222.40.234   
12          tholt@hotmail.com       Surveyor, quantity  236.71.234.240   
22  chambersmichael@gmail.com           Retail manager   65.106.61.141   

   Language  Purchase Price  
11       en           19.26  
12       en           39.65  
22       en           33.62

In [199]:
ecom[ecom['Language'] == 'en']['Language'].count()

1098

In [203]:
ecom[ecom['Job'] == 'Lawyer']['Job'].count()

30

In [206]:
ecom['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [212]:
ecom['Job'].value_counts().head(5)

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: Job, dtype: int64

In [215]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

In [218]:
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [221]:
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price']> 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [224]:
ecom[ecom['CC Exp Date'] == 25].count()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [229]:
ecom[ecom['CC Exp Date'].apply(lambda exp: exp[3:] == '25')]

Address    Lot AM or PM  \
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
5     7502 Powell Mission Apt. 768\nTravisland, VA 3...  21 XT       PM   
7     260 Rachel Plains Suite 366\nCastroberg, WV 24...  96 pG       PM   
13    118 Melton Via Suite 681\nAlexanderbury, FL 32104  36 bu       PM   
15       31730 Chelsea Crest\nBlakemouth, CT 90395-0620  41 Cj       PM   
...                                                 ...    ...      ...   
9955      66539 Potts Forge\nCartershire, AK 58271-5180  37 KB       AM   
9963  3865 Davis Meadow Suite 915\nPort Stacieview, ...  11 fo       AM   
9993  7555 Larson Locks Suite 229\nEllisburgh, MA 34...  72 jg       PM   
9994       6276 Rojas Hollow\nLake Louis, WY 56410-7837  93 Ex       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   

                                           Browser Info  \
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   
5     Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...   
7     Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...   
13    Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...   
15    Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....   
...                                                 ...   
9955  Mozilla/5.0 (compatible; MSIE 8.0; Windows CE;...   
9963  Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...   
9993  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...   
9994  Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   

                        Company       Credit Card CC Exp Date  \
4     Brown, Watson and Andrews  6011456623207998       10/25   
5                Silva-Anderson    30246185196287       07/25   
7              Marshall-Collins      561252141909       06/25   
13                   Keller PLC  4603635169938574       01/25   
15                Garcia-Steele   180069437020404       04/25   
...                         ...               ...         ...   
9955                Russell PLC     4716539058450       02/25   
9963    Brown, Gentry and White  4295151255424068       07/25   
9993             Colon and Sons    30025560104631       10/25   
9994               Ritter-Smith  3112186784121077       01/25   
9996   Hale, Collins and Wilson   210033169205009       07/25   

      CC Security Code                  CC Provider  \
4                  678  Diners Club / Carte Blanche   
5                 7169                     Discover   
7                  256                VISA 13 digit   
13                 557                VISA 16 digit   
15                 404  Diners Club / Carte Blanche   
...                ...                          ...   
9955              2805                 JCB 16 digit   
9963               764                 JCB 15 digit   
9993               629                      Maestro   
9994              1823                      Maestro   
9996               207                 JCB 16 digit   

                                      Email  \
4               christopherwright@gmail.com   
5                         ynguyen@gmail.com   
7                      phillip48@parks.info   
13                      caitlin57@yahoo.com   
15                       amanda39@yahoo.com   
...                                     ...   
9955  matthewcontreras@bradshaw-skinner.com   
9963                       zjames@gmail.com   
9993              chelseawilliams@lopez.biz   
9994                     iroberts@gmail.com   
9996                     mary85@hotmail.com   

                                       Job      IP Address Language  \
4                              Fine artist    24.140.33.94       es   
5                        Fish farm manager   55.96.152.147       ru   
7                          Event organiser  224.247.97.150       pt   
13    Accountant, chartered public finance    84.212.92.11       it   
15                          Retail manager   53.176.235.33       el   
...  